In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Flatten , Embedding

In [2]:
reviews = ["nice food",
           "amazing restaurant",
           "too good",
           "just loved it!",
           "will go again",
           "horrible food",
           "never go there",
           "poor service",
           "poor quality",
           "needs improvement"
           ]
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [7]:
one_hot("nice food",30) ## 30 is vocab size

[13, 21]

In [8]:
vocab_size = 30
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[13, 21],
 [9, 1],
 [6, 8],
 [15, 3, 2],
 [13, 15, 17],
 [19, 21],
 [1, 15, 15],
 [9, 20],
 [9, 6],
 [12, 19]]

In [10]:
#### Padding is useful for making the length and width equal
max_length = 3
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding="post")
padded_reviews

array([[13, 21,  0],
       [ 9,  1,  0],
       [ 6,  8,  0],
       [15,  3,  2],
       [13, 15, 17],
       [19, 21,  0],
       [ 1, 15, 15],
       [ 9, 20,  0],
       [ 9,  6,  0],
       [12, 19,  0]], dtype=int32)

In [18]:
embedded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation="sigmoid"))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
X = padded_reviews
y = sentiment

In [20]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
model.fit(X,y,epochs=50,verbose=0)

In [23]:
loss , accuracy = model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 235ms/step - accuracy: 0.9000 - loss: 0.6482


0.8999999761581421

In [25]:
w = model.get_layer("embedding").get_weights()[0]
len(w)

30

In [26]:
w[13]

array([-0.06538971,  0.02227314, -0.04497688,  0.02481359], dtype=float32)

In [27]:
w[9]

array([ 0.0617383 , -0.05037401,  0.0294554 , -0.00520928], dtype=float32)