In [7]:
import tensorflow as tf

In [8]:
daily_sales = [34,54,23,65,75,-1]

In [9]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [11]:
for sales in tf_dataset:
  print(sales.numpy())

34
54
23
65
75
-1


In [12]:
for sales in tf_dataset:
  print(sales)

tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(54, shape=(), dtype=int32)
tf.Tensor(23, shape=(), dtype=int32)
tf.Tensor(65, shape=(), dtype=int32)
tf.Tensor(75, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)


In [14]:
for sales in tf_dataset.take(3):
  print(sales)

tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(54, shape=(), dtype=int32)
tf.Tensor(23, shape=(), dtype=int32)


In [15]:
##Filtering Number
tf_dataset = tf_dataset.filter(lambda x : x>0)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

34
54
23
65
75


In [18]:
### Map

tf_dataset = tf_dataset.map(lambda x : x*72)
for sales in tf_dataset:
  print(sales.numpy())

2448
3888
1656
4680
5400


In [19]:
## Shuffle
tf_dataset = tf_dataset.shuffle(buffer = 3)
for sales in tf_dataset:
  print(sales.numpy())

1656
2448
4680
5400
3888


In [22]:
## Batches
for sales in tf_dataset.batch(3):
  print(sales.numpy())

[3888 4680 1656]
[5400 2448]


In [23]:
### Pipeline
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales)
tf_dataset = tf_dataset.filter(lambda x : x>0).map(lambda y : y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)


[2448 3888]
[1656 4680]
[5400]


In [29]:
import os
os.getcwd()

'/content'

In [31]:
images_ds = tf.data.Dataset.list_files("/content/Images/*/*" , shuffle=False)
for img in images_ds.take(5):
  print(img.numpy())

b'/content/Images/Cat/10001.jpg'
b'/content/Images/Cat/10002.jpeg'
b'/content/Images/Cat/10003.jpg'
b'/content/Images/Cat/10004.jpg'
b'/content/Images/Cat/10005.jpg'


In [33]:
images_ds = images_ds.shuffle(200)
for img in images_ds.take(3):
  print(img.numpy())

b'/content/Images/Dog/10010.jpg'
b'/content/Images/Dog/10007.jpg'
b'/content/Images/Cat/10017.jpg'


In [34]:
class_names = ["cat" , "dog"]

In [36]:
img_count = len(images_ds)
img_count

36

In [37]:
train_size = int(img_count*0.8)
train_size

28

In [39]:
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [40]:
len(train_ds) , len(test_ds)

(28, 8)

In [51]:
t = "MY name is Hamza"
x = t.split(" ")
x[-1]

'Hamza'

In [60]:
def get_label(file_path):
  import os
  return tf.strings.split(file_path,os.path.sep)[-2]

In [62]:
def process_img(file_path):
  label = get_label(file_path)
  img = tf.io.read_file(file_path)
  img = tf.image.decode_jpeg(img)
  img = tf.image.resize(img,[128,128])
  return img , label

In [53]:
for t in train_ds.take(4):
  print(t.numpy())

b'/content/Images/Cat/10017.jpg'
b'/content/Images/Cat/10009.jpg'
b'/content/Images/Dog/10008.jpg'
b'/content/Images/Dog/10015.jpg'


In [65]:
train_ds = train_ds.map(process_img)
for img , label in train_ds.take(3):
  print("Image: " , img)
  print("Label: ",label)

Image:  tf.Tensor(
[[[ 31.203125   29.203125   17.203125 ]
  [ 24.73172    22.73172    10.73172  ]
  [ 17.190887   15.190887    3.1908875]
  ...
  [ 44.983337   69.07474    24.993225 ]
  [ 42.16391    72.64453    24.83078  ]
  [ 39.509583   76.874115   26.       ]]

 [[ 27.691406   25.691406   13.691406 ]
  [ 22.371094   20.371094    8.371094 ]
  [ 15.998444   13.998444    2.1328125]
  ...
  [ 45.13437    71.49219    25.175781 ]
  [ 42.132965   74.42969    24.679688 ]
  [ 39.91281    79.41531    26.654999 ]]

 [[ 29.487762   26.487762   17.487762 ]
  [ 25.355469   22.355469   13.355469 ]
  [ 20.259125   17.259125    8.259125 ]
  ...
  [ 46.         74.53906    24.152344 ]
  [ 42.773438   78.25       24.238281 ]
  [ 40.18802    82.44479    26.558594 ]]

 ...

 [[204.44351   197.91226   174.9396   ]
  [221.04544   215.71967   192.65637  ]
  [228.73828   225.54037   204.84244  ]
  ...
  [217.49231   220.10818   210.72928  ]
  [227.0452    228.26474   215.88351  ]
  [227.99918   231.33017 

In [64]:
def scale(image,label):
  return image/255 , label

In [67]:
train_ds = train_ds.map(scale)
for image , label  in train_ds.take(5):
  print("Image: " , image.numpy()[0][0])
  print("Label: " , label.numpy())

Image:  [0.92941177 0.92941177 0.92941177]
Label:  b'Dog'
Image:  [0.66122216 0.27298686 0.18279079]
Label:  b'Cat'
Image:  [0.41547823 0.48998803 0.51351744]
Label:  b'Cat'
Image:  [0.3882353  0.21960784 0.25490198]
Label:  b'Cat'
Image:  [0.         0.5058824  0.69803923]
Label:  b'Cat'
